/*
 * LCD Image Converter. Converts images and fonts for embedded applciations.
 * Copyright (C) 2012 riuson
 * mailto: riuson@gmail.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/
 */

#include "revisioninfo.h"
//-----------------------------------------------------------------------------
#include <QFile>
#include <QTextStream>
#include <QRegExp>
#include "resources/revision.h"
//-----------------------------------------------------------------------------
// info generated by version-gen.sh to file resources/revision.h
//-----------------------------------------------------------------------------
bool RevisionInfo::getRevisionData(QString *hash, QString *date, QString *version)
{
    bool result = true;
#ifdef GIT_REVISION_ABBR
    *hash = QString(GIT_REVISION_ABBR);
#else
    *hash = QString("unknown");
    result = false;
#endif

#ifdef GIT_COMMIT_ADATE
    *date = QString(GIT_COMMIT_ADATE);
#else
    *date = QString("???");
    result = false;
#endif

#ifdef GIT_COMMIT_AT
    quint32 timestamp = GIT_COMMIT_AT;
    *version = QString("2.1.%1.%2").arg(timestamp >> 16).arg(timestamp & 0x0000ffff);
#else
    *version = QString("2.1.x.x");
    result = false;
#endif
    return result;
}
//-----------------------------------------------------------------------------
